nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: [ ]
        allow_headers: [ ]
        allow_methods: [ ]
        expose_headers: [ ]
        max_age: 0
        hosts: [ ]
        origin_regex: false
        forced_allow_origin_value: ~

    paths:
        '^/api/':
            allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
            allow_headers: [ 'Content-Type', 'Authorization','Preload', 'Fields', 'X-Custom-Auth','Origin','Access-Control-Allow-Origin', 'X-Requested-With', 'Content', 'Accept', 'X-LOCALE' ]
            origin_regex: true
            #forced_allow_origin_value: '*'
            allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS' ]
            expose_headers: [ 'Link' ]
        '^/cv':
            allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
            allow_headers: [ 'Content-Type', 'Authorization','Preload', 'Fields', 'X-Custom-Auth','Origin','Access-Control-Allow-Origin', 'X-Requested-With', 'Content', 'Accept', 'X-LOCALE' ]
            origin_regex: true
            allow_methods: [ 'GET' ]
            expose_headers: [ 'Link' ]
        '^/':
            origin_regex: true
            allow_origin: [ '^http://localhost:[0-9]+' ]
            allow_headers: [ 'X-Custom-Auth' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600
            hosts: [ '^api\.' ]