nelmio_cors:
  defaults:
    allow_credentials: true
    origin_regex: true
    allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
    forced_allow_origin_value: ~
  paths:
    "^/api/":
      allow_credentials: true
      origin_regex: true
      #allow_origin: ['(http|https):\/\/picassohouessou\.com']
      allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
      allow_headers: ["Content-Type", "Authorization"]
      expose_headers: ["Link"]
      max_age: 5
