vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        cv:
            uri_prefix: /media
            upload_destination: "%kernel.project_dir%/public/uploads/cv"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        media_object:
            uri_prefix: /media
            upload_destination: "%kernel.project_dir%/public/uploads/media"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
