vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    storage: flysystem
    mappings:
        cv:
            uri_prefix: /uploads/cv
            upload_destination: cv.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        media_object:
            uri_prefix: /uploads/media
            upload_destination: media.storage
            #upload_destination: "%kernel.project_dir%/public/uploads/media"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true
