# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    myEmail: "picasso@picassohouessou.com"
    no-reply_email: "noreply@picassohouessou.com"
    google_recaptcha_site_key: "%env(GOOGLE_RECAPTCHA_SITE_KEY)%"
    yahoo_email: "%env(YAHOO_EMAIL)%"
    locale: "en"
    app_locales:
        - en
        - fr
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $noReplyEmail: "%no-reply_email%"
            $projectDirectory: "%kernel.project_dir%"
            $myEmail: "%myEmail%"
            $locales: "%app_locales%"
            $defaultLocale: "%locale%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"
            - "../src/Tests/"
    # ..
    App\State\ContactUsPostProcessor:
        arguments:
            $persistProcessor: "@api_platform.doctrine.orm.state.persist_processor"
            $removeProcessor: "@api_platform.doctrine.orm.state.remove_processor"
            $mailer: "@mailer"
        tags: [ "api_platform.state_processor" ]

    #App\Serializer\MediaObjectNormalizer:
    #    tags: [ 'serializer.normalizer' ]

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: "../src/Controller/"
        tags: [ "controller.service_arguments" ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\DataFixtures\Processor\UserProcessor: ~
    #    Gedmo\Mapping\Driver\AttributeReader: ~
    #    Gedmo\Mapping\Driver\AttributeAnnotationReader: ~
    #    App\DataFixtures\Processor\TranslationProcessor:
    #        $reader: '@Gedmo\Mapping\Driver\AttributeAnnotationReader'
    App\DataFixtures\Provider\MediaProvider:
        tags: [ { name: nelmio_alice.faker.provider } ]